import type { ITrendingSection } from './types';

export const TRENDING_SECTIONS: ITrendingSection[] = [
  {
    id: 'popular',
    styles: [
      { id: 'nyan-classic', imageSrc: '/cats/catty.gif', badges: ['hot'], tagKeys: ['nyan', 'classic', 'rainbow'] },
      { id: 'cute-cat', imageSrc: '/cats/cute-cat.gif', badges: ['hot'], tagKeys: ['cute', 'pink'] },
      { id: 'glitch-cat', imageSrc: '/cats/glitch-cat.gif', badges: ['hot'], tagKeys: ['glitch', 'pixel'] },
      { id: 'pixel-cat', imageSrc: '/cats/pixel-cat.gif', badges: [], tagKeys: ['pixel', 'retro'] },
      { id: 'cute-kawaii', imageSrc: '/cats/cute-kawaii.gif', badges: [], tagKeys: ['kawaii', 'cute', 'pink'] },
      { id: 'gatito', imageSrc: '/cats/gatito.gif', badges: [], tagKeys: ['cute', 'orange'] },
    ],
  },
  {
    id: 'trending',
    styles: [
      { id: 'garfield', imageSrc: '/cats/cat-garfield.gif', badges: ['hot'], tagKeys: ['orange', 'classic'] },
      {
        id: 'cute-bunny',
        imageSrc: '/trending/cute-bunny.gif',
        badges: ['hot', 'custom'],
        tagKeys: ['bunny', 'cute'],
      },
      {
        id: 'pixel-tiger',
        imageSrc: '/trending/pixel-tiger (1).gif',
        badges: ['hot', 'custom'],
        tagKeys: ['tiger', 'pixel', 'retro'],
      },
      {
        id: 'cute-dog',
        imageSrc: '/trending/cute-dog.gif',
        badges: ['hot', 'custom'],
        tagKeys: ['dog', 'cute'],
      },
      {
        id: 'anatroll',
        imageSrc: '/trending/anatroll.gif',
        badges: ['custom'],
        tagKeys: ['creature', 'cute'],
      },
      {
        id: 'pixel-dogs',
        imageSrc: '/trending/pixel-dogs (2).gif',
        badges: ['custom'],
        tagKeys: ['dog', 'pixel', 'retro'],
      },
    ],
  },
  {
    id: 'new',
    paginated: true,
    styles: [
      {
        id: 'rolling-cat',
        imageSrc: '/cats/rolling-cat.gif',
        badges: ['new'],
        tagKeys: ['pixel', 'cute'],
      },
      {
        id: 'dancing-kitty',
        imageSrc: '/cats/cat-cats.gif',
        badges: ['new'],
        tagKeys: ['dance', 'cute'],
      },
      {
        id: 'snow-kitten',
        imageSrc: '/cats/cat-cute.gif',
        badges: ['new'],
        tagKeys: ['pixel', 'cute'],
      },
      {
        id: 'scarf-cat',
        imageSrc: '/cats/cat-in-a-scarf.gif',
        badges: ['new'],
        tagKeys: ['cozy', 'kawaii'],
      },
      {
        id: 'night-walker',
        imageSrc: '/cats/cat-walking.gif',
        badges: ['new'],
        tagKeys: ['dark', 'minimal'],
      },
      {
        id: 'happy-cat',
        imageSrc: '/cats/happy-cat.gif',
        badges: ['new'],
        tagKeys: ['kawaii', 'cute'],
      },
      {
        id: 'chubby-cat',
        imageSrc: '/cats/kitty-scratch.gif',
        badges: ['new'],
        tagKeys: ['cartoon', 'cute'],
      },
      {
        id: 'shadow-cat',
        imageSrc: '/cats/shadow-cat.gif',
        badges: ['new'],
        tagKeys: ['dark', 'minimal'],
      },
      {
        id: 'pixel-corgi',
        imageSrc: '/cats/pixel-corgi.gif',
        badges: ['new'],
        tagKeys: ['dog', 'pixel'],
      },
      {
        id: 'puppy-love',
        imageSrc: '/cats/puppy-love.gif',
        badges: ['new'],
        tagKeys: ['dog', 'kawaii'],
      },
      {
        id: 'running-pug',
        imageSrc: '/cats/pug-running.gif',
        badges: ['new'],
        tagKeys: ['dog', 'pixel', 'retro'],
      },
      {
        id: 'music-fox',
        imageSrc: '/cats/fox-music.gif',
        badges: ['new'],
        tagKeys: ['fox', 'music'],
      },
      {
        id: 'rainbow-bird',
        imageSrc: '/cats/rainbow-bird.gif',
        badges: ['new'],
        tagKeys: ['bird', 'rainbow'],
      },
      {
        id: 'ramen-shark',
        imageSrc: '/cats/ramen-shark.gif',
        badges: ['new'],
        tagKeys: ['shark', 'cartoon'],
      },
      {
        id: 'cartoon-cat',
        imageSrc: '/cats/cute-cat-cartoon.gif',
        badges: ['new'],
        tagKeys: ['cartoon', 'cute'],
      },
      {
        id: 'parrot-pixel',
        imageSrc: '/trending/parrot-pixel.gif',
        badges: ['new', 'custom'],
        tagKeys: ['bird', 'pixel', 'retro'],
      },
      {
        id: 'fawn',
        imageSrc: '/cats/fawn-run.gif',
        badges: ['new'],
        tagKeys: ['deer', 'minimal'],
      },
      {
        id: 'osito',
        imageSrc: '/trending/milk-and-mocha.gif',
        badges: ['new', 'custom'],
        tagKeys: ['bear', 'cute'],
      },
      {
        id: 'japan-creature',
        imageSrc: '/trending/cute-japan-creature.gif',
        badges: ['new', 'custom'],
        tagKeys: ['creature', 'kawaii'],
      },
      {
        id: 'purple-bat',
        imageSrc: '/cats/purple-bat.gif',
        badges: ['new'],
        tagKeys: ['bat', 'minimal'],
      },
      {
        id: 'cute-bunny',
        imageSrc: '/trending/cute-bunny.gif',
        badges: ['new', 'custom'],
        tagKeys: ['bunny', 'cute'],
      },
      {
        id: 'pixel-tiger',
        imageSrc: '/trending/pixel-tiger (1).gif',
        badges: ['new', 'custom'],
        tagKeys: ['tiger', 'pixel', 'retro'],
      },
      {
        id: 'cute-dog',
        imageSrc: '/trending/cute-dog.gif',
        badges: ['new', 'custom'],
        tagKeys: ['dog', 'cute'],
      },
      {
        id: 'anatroll',
        imageSrc: '/trending/anatroll.gif',
        badges: ['new', 'custom'],
        tagKeys: ['creature', 'cute'],
      },
      {
        id: 'pixel-dogs',
        imageSrc: '/trending/pixel-dogs (2).gif',
        badges: ['new', 'custom'],
        tagKeys: ['dog', 'pixel', 'retro'],
      },
    ],
  },
  {
    id: 'collections',
    collections: [
      { id: 'classic', coverImageSrc: '/cats/catty.gif', itemCount: 4 },
      { id: 'pixel', coverImageSrc: '/cats/pixel-cat.gif', itemCount: 3 },
      { id: 'kawaii', coverImageSrc: '/cats/cute-kawaii.gif', itemCount: 4 },
      { id: 'dance', coverImageSrc: '/cats/orange-cat-dancing.gif', itemCount: 3 },
      { id: 'monochrome', coverImageSrc: '/cats/black.gif', itemCount: 2 },
      { id: 'orange', coverImageSrc: '/cats/cat-garfield.gif', itemCount: 4 },
    ],
  },
];
